const cfg=window.HUB_CONFIG,$=s=>document.querySelector(s),AUTH=cfg.supabaseUrl+"/auth/v1";let mode="login"; if(cfg.mode==="acceptance"){const b=$("#acceptanceBanner");if(b)b.hidden=false;}
function setMode(x){mode=x;$("#submit").textContent=x==="signup"?"Создать аккаунт":"Войти";$("#tabSignup").classList.toggle("active",x==="signup");$("#tabLogin").classList.toggle("active",x==="login");$("#message").textContent=""}
$("#tabLogin").onclick=()=>setMode("login");$("#tabSignup").onclick=()=>setMode("signup");
function render(u){$("#auth").hidden=!!u;$("#account").hidden=!u;if(u){$("#userEmail").textContent=u.email||"—";if(cfg.mode==="acceptance"){const p=$("#prepareAi");if(p)p.hidden=true;const h=document.querySelector(".connectHelp");if(h)h.hidden=true;runAcceptanceBootstrap().catch(e=>{$("#connectMessage").textContent="Acceptance: "+e.message});return}loadConnections().catch(()=>{});const q=new URLSearchParams(location.search),ret=q.get("oauth_return");if(ret){q.delete("oauth_return");history.replaceState(null,"",location.pathname+(q.size?"?"+q:""));location.assign(ret)}}}
async function post(path,body){const r=await fetch(AUTH+path,{method:"POST",headers:{"apikey":cfg.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||("HTTP "+r.status));return d}
$("#form").onsubmit=async e=>{e.preventDefault();const b=$("#submit"),m=$("#message");b.disabled=true;m.textContent="";try{const email=$("#email").value.trim(),password=$("#password").value;if(mode==="signup"){const d=await post("/signup",{email,password});if(d.access_token){saveSession(d);render(d.user)}else{m.textContent="Аккаунт создан. Подтвердите email.";$("#resend").hidden=false}}else{const d=await post("/token?grant_type=password",{email,password});saveSession(d);render(d.user)}}catch(e){m.textContent=e.message}finally{b.disabled=false}};
$("#resend").onclick=async()=>{try{await post("/resend",{type:"signup",email:$("#email").value.trim()});$("#message").textContent="Письмо отправлено повторно."}catch(e){$("#message").textContent=e.message}};
function saveSession(d){if(d.access_token)localStorage.setItem("hub_access_token",d.access_token);if(d.refresh_token)localStorage.setItem("hub_refresh_token",d.refresh_token);if(d.user)localStorage.setItem("hub_user",JSON.stringify(d.user))}
async function accessToken(){let token=localStorage.getItem("hub_access_token");if(token){try{const part=token.split(".")[1],p=JSON.parse(atob(part.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(part.length/4)*4,"=")));if((p.exp||0)>Math.floor(Date.now()/1000)+60)return token}catch{}}const refresh_token=localStorage.getItem("hub_refresh_token");if(!refresh_token)throw new Error("Нет сохранённой сессии");const d=await post("/token?grant_type=refresh_token",{refresh_token});saveSession(d);return d.access_token}
$("#logout").onclick=()=>{localStorage.removeItem("hub_access_token");localStorage.removeItem("hub_refresh_token");localStorage.removeItem("hub_user");render(null)};
async function mcp(name,args={}){const token=await accessToken();const r=await fetch(cfg.supabaseUrl+"/functions/v1/mcp-gateway/rpc",{method:"POST",headers:{"Authorization":"Bearer "+token,"apikey":cfg.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify({name,arguments:args})});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw new Error("Hub non-JSON "+r.status+": "+raw.slice(0,160))}if(!r.ok||d.error)throw new Error(d.error||("Hub HTTP "+r.status));if(!Object.prototype.hasOwnProperty.call(d,"result"))throw new Error("Hub response без result: "+JSON.stringify(d).slice(0,200));return d.result}
async function bootstrap(){const b=$("#bootstrapAgent"),m=$("#bootstrapMessage");b.disabled=true;m.textContent="1/5 Проверка Hub…";try{let agents=await mcp("agent_list");m.textContent="2/5 Agent A…";let agent=(Array.isArray(agents)?agents:[]).find(a=>a.agent_key==="hub-web-agent-a");if(!agent)agent=await mcp("agent_register",{agent_key:"hub-web-agent-a",name:"Agent A",description:"Hub Core first tenant E2E",provider:"hub-web",metadata:{purpose:"continuity-e2e"}});if(!agent?.id)throw new Error("Agent A не создан: "+JSON.stringify(agent));m.textContent="3/5 Raw history…";const conv=await mcp("conversation_create",{title:"Hub Core Agent A E2E",agent_id:agent.id,metadata:{test:"agent-a"}});await mcp("message_append",{conversation_id:conv.id,agent_id:agent.id,role:"USER",content:{text:"AGENT_A_HISTORY_OK"},source:"hub-web",idempotency_key:"agent-a-history-"+conv.id});m.textContent="4/5 Memory…";await mcp("memory_remember",{scope:"personal",agent_id:agent.id,type:"E2E_TEST",title:"Agent A continuity",content:{marker:"AGENT_A_MEMORY_OK",conversation_id:conv.id},confidence:1});m.textContent="5/5 Context…";const ctx=await mcp("context_get",{conversation_id:conv.id,message_limit:10,memory_limit:20});const history=(ctx.messages||[]).some(x=>x.content?.text==="AGENT_A_HISTORY_OK"),memory=(ctx.personal_memory||[]).some(x=>x.content?.marker==="AGENT_A_MEMORY_OK");$("#agentName").textContent=agent.name;$("#agentId").textContent=agent.id;$("#e2eStatus").textContent=history&&memory?"PASS — history + memory":"FAIL";$("#agentInfo").hidden=false;if(!history||!memory)throw new Error("Agent A context FAIL: "+JSON.stringify({history,memory}));m.textContent="6/8 Agent B…";await bootstrapB(agent,conv)}catch(e){m.textContent="ОШИБКА: "+(e.message||e)}finally{b.disabled=false}}
$("#bootstrapAgent").onclick=bootstrap;
setMode("login");(async()=>{let cached=null;try{cached=JSON.parse(localStorage.getItem("hub_user")||"null")}catch{}if(cached)render(cached);try{const token=await accessToken();const r=await fetch(AUTH+"/user",{headers:{"Authorization":"Bearer "+token,"apikey":cfg.supabasePublishableKey}});if(!r.ok)throw new Error("HTTP "+r.status);const user=await r.json();localStorage.setItem("hub_user",JSON.stringify(user));render(user)}catch(e){if(!cached){render(null);$("#message").textContent="Войдите в Hub."}else{$("#connectMessage").textContent="Не удалось обновить сессию. Кабинет оставлен открытым; повторим автоматически при следующем запросе."}}})();
async function bootstrapB(agentA,conv){const m=$("#bootstrapMessage");m.textContent="6/8 Agent B…";let agents=await mcp("agent_list");let b=(Array.isArray(agents)?agents:[]).find(a=>a.agent_key==="hub-web-agent-b");if(!b)b=await mcp("agent_register",{agent_key:"hub-web-agent-b",name:"Agent B",description:"Hub Core continuity verifier",provider:"hub-web",metadata:{purpose:"continuity-e2e"}});if(!b?.id)throw new Error("Agent B не создан");m.textContent="7/8 Continuity…";const ctx=await mcp("context_get",{conversation_id:conv.id,message_limit:10,memory_limit:20});const history=(ctx.messages||[]).some(x=>x.content?.text==="AGENT_A_HISTORY_OK"),memory=(ctx.personal_memory||[]).some(x=>x.content?.marker==="AGENT_A_MEMORY_OK");if(!history||!memory)throw new Error("Agent B continuity FAIL: history="+history+", memory="+memory);m.textContent="8/8 PASS — Agent A → Agent B continuity";$("#agentName").textContent="Agent A + Agent B";$("#e2eStatus").textContent="PASS — A → B: history + memory"}

const DEFAULT_AGENT_GRANTS=["agent.read","conversation.read","conversation.write","memory.read","memory.write","session.read","session.write","event.read","event.write"];
$("#prepareAi").onclick=()=>{const h=document.querySelector(".connectHelp");if(h){h.open=true;h.scrollIntoView({behavior:"smooth",block:"nearest"})}$("#connectMessage").textContent="Выберите AI-клиент в инструкции ниже и подключите его через OAuth. Hub выдаст доступ только после вашего разрешения."};

async function runAcceptanceBootstrap(){
 const m=$("#connectMessage"); m.textContent="Acceptance: привязка OAuth-сессии…";
 let clientId=localStorage.getItem("hub_acceptance_client_id"); if(!clientId){clientId="hub-web-acceptance-"+crypto.randomUUID();localStorage.setItem("hub_acceptance_client_id",clientId)}
 const token=await accessToken();
 const r=await fetch(cfg.supabaseUrl+"/rest/v1/rpc/acceptance_oauth_bootstrap",{method:"POST",headers:{"Authorization":"Bearer "+token,"apikey":cfg.supabasePublishableKey,"Content-Type":"application/json","Accept-Profile":"app","Content-Profile":"app"},body:JSON.stringify({p_client_id:clientId})});
 const raw=await r.text(); if(!r.ok) throw new Error(raw.slice(0,240));
 m.textContent="Acceptance OAuth готов. Boundary-тест доступен."; if(!document.querySelector("#boundaryTest")){const b=document.createElement("button");b.id="boundaryTest";b.className="primary";b.textContent="Запустить L13/L14";b.onclick=runBoundaryTest;document.querySelector("#connections").appendChild(b)}
 const p=document.querySelector("#prepareAi"); if(p)p.hidden=true; const h=document.querySelector(".connectHelp"); if(h)h.hidden=true;
}

async function rpcApp(name,args){const token=await accessToken();const r=await fetch(cfg.supabaseUrl+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Authorization":"Bearer "+token,"apikey":cfg.supabasePublishableKey,"Content-Type":"application/json","Accept-Profile":"app","Content-Profile":"app"},body:JSON.stringify(args||{})});if(!r.ok)throw new Error(name+" HTTP "+r.status);return await r.json().catch(()=>null)}
async function runBoundaryTest(){const m=$("#connectMessage"),owner="9cec7015-8d5b-4d92-8abe-f981017b15a5",project="44000000-0000-0000-0000-000000000001";try{m.textContent="L13/L14 выполняется…";await rpcApp("acceptance_l13_l14_fixture",{p_mode:"both"});await rpcApp("acceptance_l13_l14_fixture",{p_mode:"revoke_lobby"});const l13Lobby=await rpcApp("lobby_guest_access_v1",{p_owner_user_id:owner});const l13Project=await rpcApp("project_space_get",{p_project_space_id:project});const l13=(!l13Lobby||l13Lobby.length===0)&&!!l13Project;await rpcApp("acceptance_l13_l14_fixture",{p_mode:"lobby_only"});const l14Lobby=await rpcApp("lobby_guest_access_v1",{p_owner_user_id:owner});let denied=false;try{const x=await rpcApp("project_space_get",{p_project_space_id:project});denied=!x||(Array.isArray(x)&&x.length===0)}catch{denied=true}const lobbyOk=Array.isArray(l14Lobby)?l14Lobby.some(x=>x===true||x?.allowed===true):l14Lobby===true||l14Lobby?.allowed===true;const l14=lobbyOk&&denied;await rpcApp("acceptance_l13_l14_fixture",{p_mode:"restore"});m.innerHTML="<b>L13 Project without Lobby: "+(l13?"PASS":"FAIL")+"</b><br><b>L14 Lobby access: "+(lobbyOk?"PASS":"FAIL")+"</b><br><b>L14 Project denied: "+(denied?"PASS":"FAIL")+"</b><br><small>Lobby raw: "+JSON.stringify(l14Lobby).replace(/</g,"&lt;")+"</small>";}catch(e){m.textContent="Boundary test: "+e.message}}
