const cfg=window.HUB_CONFIG,$=s=>document.querySelector(s),AUTH=cfg.supabaseUrl+"/auth/v1";let mode="login";
function setMode(x){mode=x;$("#nameWrap").hidden=x!=="signup";$("#submit").textContent=x==="signup"?"Создать аккаунт":"Войти";$("#tabSignup").classList.toggle("active",x==="signup");$("#tabLogin").classList.toggle("active",x==="login");$("#message").textContent=""}
$("#tabLogin").onclick=()=>setMode("login");$("#tabSignup").onclick=()=>setMode("signup");
function render(u){$("#auth").hidden=!!u;$("#account").hidden=!u;if(u){$("#userEmail").textContent=u.email||"—"}}
async function post(path,body){const r=await fetch(AUTH+path,{method:"POST",headers:{"apikey":cfg.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||("HTTP "+r.status));return d}
$("#form").onsubmit=async e=>{e.preventDefault();const b=$("#submit"),m=$("#message");b.disabled=true;m.textContent="";try{const email=$("#email").value.trim(),password=$("#password").value;if(mode==="signup"){const d=await post("/signup",{email,password,data:$("#name").value.trim()?{name:$("#name").value.trim()}:undefined});if(d.access_token){localStorage.hub_access_token=d.access_token;localStorage.hub_user=JSON.stringify(d.user);render(d.user)}else{m.textContent="Аккаунт создан. Подтвердите email.";$("#resend").hidden=false}}else{const d=await post("/token?grant_type=password",{email,password});localStorage.hub_access_token=d.access_token;localStorage.hub_user=JSON.stringify(d.user);render(d.user)}}catch(e){m.textContent=e.message}finally{b.disabled=false}};
$("#resend").onclick=async()=>{try{await post("/resend",{type:"signup",email:$("#email").value.trim()});$("#message").textContent="Письмо отправлено повторно."}catch(e){$("#message").textContent=e.message}};
$("#logout").onclick=()=>{localStorage.removeItem("hub_access_token");localStorage.removeItem("hub_user");render(null)};
$("#bootstrapAgent").onclick=()=>{$("#bootstrapMessage").textContent="Клик Agent A работает. Следующий этап MCP.";};
setMode("login");try{render(JSON.parse(localStorage.hub_user||"null"))}catch{render(null)}