const cfg=window.HUB_CONFIG,$=s=>document.querySelector(s),AUTH=cfg.supabaseUrl+"/auth/v1";let mode="login";
function setMode(x){mode=x;$("#nameWrap").hidden=x!=="signup";$("#submit").textContent=x==="signup"?"Создать аккаунт":"Войти";$("#tabSignup").classList.toggle("active",x==="signup");$("#tabLogin").classList.toggle("active",x==="login");$("#message").textContent=""}
$("#tabLogin").onclick=()=>setMode("login");$("#tabSignup").onclick=()=>setMode("signup");
function render(u){$("#auth").hidden=!!u;$("#account").hidden=!u;if(u){$("#userEmail").textContent=u.email||"—"}}
async function post(path,body){const r=await fetch(AUTH+path,{method:"POST",headers:{"apikey":cfg.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||("HTTP "+r.status));return d}
$("#form").onsubmit=async e=>{e.preventDefault();const b=$("#submit"),m=$("#message");b.disabled=true;m.textContent="";try{const email=$("#email").value.trim(),password=$("#password").value;if(mode==="signup"){const d=await post("/signup",{email,password,data:$("#name").value.trim()?{name:$("#name").value.trim()}:undefined});if(d.access_token){localStorage.hub_access_token=d.access_token;localStorage.hub_user=JSON.stringify(d.user);render(d.user)}else{m.textContent="Аккаунт создан. Подтвердите email.";$("#resend").hidden=false}}else{const d=await post("/token?grant_type=password",{email,password});localStorage.hub_access_token=d.access_token;localStorage.hub_user=JSON.stringify(d.user);render(d.user)}}catch(e){m.textContent=e.message}finally{b.disabled=false}};
$("#resend").onclick=async()=>{try{await post("/resend",{type:"signup",email:$("#email").value.trim()});$("#message").textContent="Письмо отправлено повторно."}catch(e){$("#message").textContent=e.message}};
$("#logout").onclick=()=>{localStorage.removeItem("hub_access_token");localStorage.removeItem("hub_user");render(null)};
async function mcp(name,args={}){const token=localStorage.getItem("hub_access_token");if(!token)throw new Error("Нет активной сессии");const r=await fetch(cfg.supabaseUrl+"/functions/v1/mcp-gateway/rpc",{method:"POST",headers:{"Authorization":"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({name,arguments:args})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||("Hub HTTP "+r.status));return d.result}
async function bootstrap(){const b=$("#bootstrapAgent"),m=$("#bootstrapMessage");b.disabled=true;m.textContent="1/5 Проверка Hub…";try{let agents=await mcp("agent_list");m.textContent="2/5 Agent A…";let agent=(Array.isArray(agents)?agents:[]).find(a=>a.agent_key==="hub-web-agent-a");if(!agent)agent=await mcp("agent_register",{agent_key:"hub-web-agent-a",name:"Agent A",description:"Hub Core first tenant E2E",provider:"hub-web",metadata:{purpose:"continuity-e2e"}});m.textContent="3/5 Raw history…";const conv=await mcp("conversation_create",{title:"Hub Core Agent A E2E",agent_id:agent.id,metadata:{test:"agent-a"}});await mcp("message_append",{conversation_id:conv.id,agent_id:agent.id,role:"USER",content:{text:"AGENT_A_HISTORY_OK"},source:"hub-web",idempotency_key:"agent-a-history-"+conv.id});m.textContent="4/5 Memory…";await mcp("memory_remember",{scope:"personal",agent_id:agent.id,type:"E2E_TEST",title:"Agent A continuity",content:{marker:"AGENT_A_MEMORY_OK",conversation_id:conv.id},confidence:1});m.textContent="5/5 Context…";const ctx=await mcp("context_get",{conversation_id:conv.id,message_limit:10,memory_limit:20});const history=(ctx.messages||[]).some(x=>x.content?.text==="AGENT_A_HISTORY_OK"),memory=(ctx.personal_memory||[]).some(x=>x.content?.marker==="AGENT_A_MEMORY_OK");$("#agentName").textContent=agent.name;$("#agentId").textContent=agent.id;$("#e2eStatus").textContent=history&&memory?"PASS — history + memory":"FAIL";$("#agentInfo").hidden=false;m.textContent=history&&memory?"PASS — Agent A: history + memory":"FAIL — "+JSON.stringify({history,memory})}catch(e){m.textContent="ОШИБКА: "+(e.message||e)}finally{b.disabled=false}}
$("#bootstrapAgent").onclick=bootstrap;
setMode("login");try{render(JSON.parse(localStorage.hub_user||"null"))}catch{render(null)}